language: python
python:
    - 3.5
    - 3.6
cache:
    directories:
        - $HOME/.pip-cache
        - $HOME/.pip-accel
install:
    - pip3 install pip-accel --cache-dir $HOME/.pip-cache
    - pip-accel install -r test-requirements.txt
script:
    - bash scripts/flake.sh
    - bash scripts/nose.sh
sudo: false
