language: python
python:
    - 3.6
cache:
    directories:
        - $HOME/.pip-cache
        - $HOME/.pip-accel
install:
    - pip3 install pip-accel --cache-dir $HOME/.pip-cache
    - pip-accel install -r test-requirements.txt
before_script:
    - bash flake.sh
sudo: false
