environment:
    matrix:
        - PYTHON: C:\\Python35\\python.exe

platform:
    - x86
    - x64

branches:
    only:
        - master
        - appveyor

install:
    - "%PYTHON% -m pip install -r requirements.txt"

build_script:
    - "%PYTHON% build_executable.py build"

artifacts:
    - path: build

